FROM tensorflow/tensorflow:2.8.0-gpu
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /conv/
WORKDIR /conv
ADD monthlyPredict.py /conv
ADD monthlyUtil.py /conv
ADD requirements.txt /conv
RUN pip install -r requirements.txt
ENTRYPOINT [ "python", "MonthlyPredict.py" ]